import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	plugins: [
		// esbuildSvelte({
		// 	compilerOptions: { css: true },
		// 	preprocess: sveltePreprocess(),
		// })
	],
	banner: {
		js: banner,
	},
	entryPoints: ['./src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: '../../main.js',
	minify: false, // 自带词典时 9.2MB -> 8.0MB, 不自带词典时: 略
}).catch(() => process.exit(1));
