[[categories]]
label = "表格"
key = "table 表格"
detail = "md"
callback = '''
|     |     |
| --- | --- |
|     |     |

'''

[[categories]]
label = "代码块"
key = "codeblock 代码块"
detail = "md"
callback = '''
```

```

'''

[[categories]]
label = "数学块"
key = "mathblock 数学块"
detail = "md"
callback = '''
$$

$$

'''

[[categories]]
label = "脚注"
key = "footnote 脚注"
detail = "md"
callback = '''
[^1]

[^1]: 

'''
